# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'action turnstyle-python'
description: 'A GitHub Action (in python!) for serializing workflow runs'
author: 'beckermr'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
inputs:
  poll-interval-seconds:
    description: "Number of seconds to wait in between checks for previous run completion (defaults to 60)"
  continue-after-seconds:
    description: "Maximum number of seconds to wait before moving forward (unbound by default). Mutually exclusive with abort-after-seconds"
  abort-after-seconds:
    description: "Maximum number of seconds to wait before failing the step (unbound by default). Mutually exclusive with continue-after-seconds"
  github-token:
    description: 'github token'
    required: true
outputs:
  force_continued:
    description: "True if continue-after-seconds is used and the step using turnstyle continued. False otherwise."
branding:
  color: 'green'
  icon: 'git-commit'
